services:
  frontend:
    container_name: "frontend"
    image: frontend:1.0.0
    build:
      context: ./frontend
      dockerfile: next.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - hecate
  hecate:
    container_name: "hecate"
    build: .
    environment:
      - SERVER_PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data

  # Standalone PostgreSQL 16 container
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
