services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: hecate
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  hecate:
    build: .
    environment:
      - DATABASE_URL=$DATABASE_URL
      - DATABASE_PORT=$DATABASE_PORT
    depends_on:
      - db

volumes:
  postgres_data:
