services:
  frontend:
    container_name: "frontend"
    image: frontend:1.0.0
    build:
      context: ./frontend
      dockerfile: next.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - hecate
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: hecate
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  hecate:
    container_name: "hecate"
    build: .
    environment:
      - DATABASE_URL=$DATABASE_URL
      - SERVER_PORT=8000
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data:
